# Generated by Django 6.0.5 on 2026-05-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "액션"),
                            ("drama", "드라마"),
                            ("comedy", "코미디"),
                            ("thriller", "스릴러"),
                            ("romance", "로맨스"),
                            ("sf", "SF"),
                            ("horror", "공포"),
                            ("animation", "애니메이션"),
                        ],
                        max_length=20,
                    ),
                ),
                ("release_year", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("poster_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-release_year", "title"],
            },
        ),
    ]
